# Generated by Django 5.2.14 on 2026-06-03 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the doctor', max_length=150)),
                ('specialty', models.CharField(help_text='Medical specialty/department', max_length=100)),
                ('contact', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number.', regex='^[+\\d][\\d\\s\\-]{6,20}$')])),
                ('email', models.EmailField(help_text='Professional email address', max_length=254, unique=True)),
                ('experience_years', models.PositiveIntegerField(help_text='Number of years of experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('clinic_address', models.TextField(help_text='Full address of the clinic/hospital')),
                ('available_days', models.CharField(help_text='Comma‑separated list of days the doctor is available', max_length=100)),
                ('consultation_fee', models.DecimalField(decimal_places=2, help_text='Fee charged per consultation', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
    ]
