# Generated by Django 6.0.5 on 2026-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('city', models.CharField()),
            ],
        ),
    ]
