# Generated by Django 4.2 on 2026-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_id_alter_patient_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
