# Generated by Django 6.0.6 on 2026-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=25)),
            ],
        ),
    ]
