# Generated by Django 4.2.23 on 2026-06-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studinfo',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
